apiVersion: v1
kind: ConfigMap
metadata:
  name: node-server-config
  labels:
    app: server
data:
  POSTGRES_DB: vehicle_transfer_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: db
  POSTGRES_PORT: '5432'
